### PR TITLE
Rewrote the Distance text

### PR DESCRIPTION
**Pull request by iphydf**
[Review on Reviewable](https://reviewable.io/reviews/toktok/tox-spec/18)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[spec.md, line 46 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/18#-KBfh0k0-DKuXfq1ZJXv:-KBfh0k1NHdcnsIqOnYX:-475217171) ([raw file](https://github.com/toktok/tox-spec/blob/25b9ad3ba1567fe2b9e64cc378761e60eafdcb89/spec.md#L46)):_
Is it something that should be included here? I.e. that seems like unnecessary overhead, which is ~hard for someone who knows nothing about crypto to verify, and it sounds like something that one has to do manually. Considering that NaCl was supposed to be ~easy to use, and in none of public APIs that kind of stuff is mentioned, should reference go into that kind of detail?

The valid case for inclusion is that someone might slip up implementing {de-,}serialization of "crypto number"s, which wouldn't be good. On the other hand, how likely is that, considering that they're supposed to just read/write amount of bytes that "crypto number" consists of?

That issue arises from reference being tailored at NaCl – libsodium provides adequate functionality for it:
- `sodium_bin2hex()`
- `sodium_hex2bin()`

IMHO reference should be easy to use, and not point in misleading direction – i.e. the way it is now, it seemingly points in the direction where one has to take care of padding manually, which should not be the case.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/18)_

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[spec.md, line 46 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/18#-KBfh0k0-DKuXfq1ZJXv:-KBhKhrn1-NGIkazaLRZ:-1635356372) ([raw file](https://github.com/toktok/tox-spec/blob/25b9ad3ba1567fe2b9e64cc378761e60eafdcb89/spec.md#L46)):_
Rewrote it to be a little more explicit and removed the part about padding.

The zero-padding is implied by the fact that the numbers are Big Endian encoded in 32 (or 24) bytes. I just wanted it to be unambiguous, so I added that wording. It's not necessary and I agree it might confuse some people. PTAL.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/18)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[spec.md, line 51 [r2]](https://reviewable.io:443/reviews/toktok/tox-spec/18#-KBhPGqwHN6An-1Bm2dQ:-KBhPGqx9eKVW0BLlFO2:1709538607) ([raw file](https://github.com/toktok/tox-spec/blob/ff1fbaddb9110db3854cdb48327fd2827fcf25b6/spec.md#L51)):_
"is the identity function" ?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/18)_

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[spec.md, line 51 [r2]](https://reviewable.io:443/reviews/toktok/tox-spec/18#-KBhPGqwHN6An-1Bm2dQ:-KBhf9oasseMxCX4I73I:1169130007) ([raw file](https://github.com/toktok/tox-spec/blob/ff1fbaddb9110db3854cdb48327fd2827fcf25b6/spec.md#L51)):_
`f(x) = x` is the identity function, meaning: you change nothing about the data.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/18)_

**Comment by zetok** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/18)_

**Pull request merged**
