### PR TITLE
Fix friend section after update of save format

### PR DESCRIPTION
**Pull request by robinlinden**
See [#281](https://github.com/TokTok/c-toxcore/pull/281) for PR with save format update.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/spec/47)

### CODE REVIEW

**Comment by GrayHatter** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[spec.md, line 4007 at r1](https://reviewable.io:443/reviews/toktok/spec/47#-KWiYaMGgx4oXvIvno0W:-KWiYaMIzs1IBSI6CzCr:bgup4ex) ([raw file](https://github.com/toktok/spec/blob/089c0e104bf95169fae2bb41bbb5c155af393b8b/spec.md#L4007)):_

> ``` Markdown
> | `2`    | `uint16_t` Size of the friend request message (BE)         |
> | `128`  | Name as a UTF-8 encoded string                             |
> | `2`    | `uint16_t` Size of the name (BE)                           |
> ```

Size in bytes right?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/spec/47)_

**Comment by GrayHatter** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[spec.md, line 4003 at r1](https://reviewable.io:443/reviews/toktok/spec/47#-KWiYl2c4htDuWfxfGnw:-KWiYl2c4htDuWfxfGnx:b8g4r0d) ([raw file](https://github.com/toktok/spec/blob/089c0e104bf95169fae2bb41bbb5c155af393b8b/spec.md#L4003)):_

> ``` Markdown
> | `1`    | `uint8_t` Status                                           |
> | `32`   | Long term public key                                       |
> | `1024` | Friend request message as a UTF-8 encoded string           |
> ```

Does toxcore promise utf8, or valid utf8?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/spec/47)_

**Comment by robinlinden** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[spec.md, line 4003 at r1](https://reviewable.io:443/reviews/toktok/spec/47#-KWiYl2c4htDuWfxfGnw:-KWjsceHmnHN4XG2_42r:b-kbr9hc) ([raw file](https://github.com/toktok/spec/blob/089c0e104bf95169fae2bb41bbb5c155af393b8b/spec.md#L4003)):_
<details><summary>

<i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>



> Does toxcore promise utf8, or valid utf8?
> </details>
> Toxcore doesn't check what we're receiving besides that it's not too long and the spec says utf8. I think we only promise utf8.

---

_[spec.md, line 4007 at r1](https://reviewable.io:443/reviews/toktok/spec/47#-KWiYaMGgx4oXvIvno0W:-KWjlySSJCeuDaoRURT3:btqqu5l) ([raw file](https://github.com/toktok/spec/blob/089c0e104bf95169fae2bb41bbb5c155af393b8b/spec.md#L4007)):_
<details><summary>

<i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary>



> Size in bytes right?
> </details>
> Correct.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/spec/47)_

**Comment by iphydf** [comment]
Fix formatting (see https://travis-ci.org/TokTok/spec/builds/177544832#L246).

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/spec/47#-:-KX45GnuSi_uLIwK6l9r:b-jbsf8z)*

**Comment by GrayHatter** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/spec/47#-:-KX9gHDi9URaLQ8_FzLC:b-jbsf8z)*

**Pull request merged**
