### PR TITLE
Add k-buckets specification.

### PR DESCRIPTION
**Pull request by iphydf**
Ready for review now.

---

This change is [Reviewable](https://reviewable.io/reviews/toktok/tox-spec/30)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[spec.md, line 379 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/30#-KDO24XzsC8IvNIvXLhy:-KDO24Y-Z6wxxOX8zLJg:-1303998852) ([raw file](https://github.com/toktok/tox-spec/blob/8c2fc49eb098501cbfdaa5e7a01f524976c194c5/spec.md#L379)):_
s/2/1/

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/30)_

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[spec.md, line 379 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/30#-KDO24XzsC8IvNIvXLhy:-KDOJB4I-bEAz_ypFmen:-499146009) ([raw file](https://github.com/toktok/tox-spec/blob/8c2fc49eb098501cbfdaa5e7a01f524976c194c5/spec.md#L379)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/30)_

**Comment by zetok** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[spec.md, line 372 [r2]](https://reviewable.io:443/reviews/toktok/tox-spec/30#-KDOl0SriTS0TcTxZFnN:-KDOl0SriTS0TcTxZFnO:-1099118038) ([raw file](https://github.com/toktok/tox-spec/blob/9acc359865e19a8ff2e8951e67d5a7baad043d59/spec.md#L372)):_
formatting

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/30)_

**Comment by iphydf** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[spec.md, line 372 [r2]](https://reviewable.io:443/reviews/toktok/tox-spec/30#-KDOl0SriTS0TcTxZFnN:-KDYw_HljUsaf3WSklVb:-499146009) ([raw file](https://github.com/toktok/tox-spec/blob/9acc359865e19a8ff2e8951e67d5a7baad043d59/spec.md#L372)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/30)_

**Comment by zetok** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[spec.md, line 402 [r3]](https://reviewable.io:443/reviews/toktok/tox-spec/30#-KDZ0B6cigvdtH8h8mjh:-KDZ0B6dbmIJ9m-qV249:2136627440) ([raw file](https://github.com/toktok/tox-spec/blob/3a128b72ce95e2c7beb6af05ee1d1ed77968e782/spec.md#L402)):_
"the greatest entry" is a bit ambiguous, perhaps "entry furthest away from baseKey" would be better?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/30)_

**Comment by iphydf** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[spec.md, line 402 [r3]](https://reviewable.io:443/reviews/toktok/tox-spec/30#-KDZ0B6cigvdtH8h8mjh:-KDZ2W8aKAX853A9hGRQ:566770395) ([raw file](https://github.com/toktok/tox-spec/blob/3a128b72ce95e2c7beb6af05ee1d1ed77968e782/spec.md#L402)):_
Rephrased.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/30)_

**Comment by zetok** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/30)_

**Pull request merged**
