### PR TITLE
Formatting

### PR DESCRIPTION
**Pull request by iphydf**
Putting this up for review already. It includes the commit from #22, so when you review, please focus on the latest commit only.

[Review on Reviewable](https://reviewable.io/reviews/toktok/tox-spec/23)

### CODE REVIEW

**Comment by GrayHatter** [comment]
looks fine, I hate that you replaced single quotes with apostrophes but hey... 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/23#-:-KBzDuD58eksAqrqyJaV:-90180512)_

**Comment by iphydf** [comment]
Quotes thing reverted.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/23#-:-KC0FIYRg5iYnmI3ly64:-1756628715)_

**Comment by zetok** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_[.md-style.rb, line 9 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/23#-KC-v0gwzXC5amBwTdzQ:-KC-v0gxIFWF5--KIvHf:-1561403675) ([raw file](https://github.com/toktok/tox-spec/blob/32069825f4ec5a65a86c944684e1f8a9e72fec3d/.md-style.rb#L9)):_
I think that it would be good if there was some file in repository that would explain "how (& why ?)" when it comes to formatting, or point to a place where it's explained.

---

_[spec.md, line 791 [r2]](https://reviewable.io:443/reviews/toktok/tox-spec/23#-KC0fOcd-HN5pUjz_dOW:-KC0fOcd-HN5pUjz_dOX:628356293) ([raw file](https://github.com/toktok/tox-spec/blob/3afbc11a45d64c3e39b10fd0044e0905b696be02/spec.md#L791)):_
rustdoc with this:
now
before:
before

---

_[spec.md, line 1507 [r2]](https://reviewable.io:443/reviews/toktok/tox-spec/23#-KC0hY71S6QAWY9hVdBM:-KC0hY71S6QAWY9hVdBN:34824995) ([raw file](https://github.com/toktok/tox-spec/blob/3afbc11a45d64c3e39b10fd0044e0905b696be02/spec.md#L1507)):_
Starts breaking with rustdoc:
now

# 

before:
before

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/23)_

**Comment by zetok** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[spec.md, line 791 [r2]](https://reviewable.io:443/reviews/toktok/tox-spec/23#-KC0fOcd-HN5pUjz_dOW:-KC1CS5oW4QI8-mC0P3P:-525378891) ([raw file](https://github.com/toktok/tox-spec/blob/3afbc11a45d64c3e39b10fd0044e0905b696be02/spec.md#L791)):_
Now it's 


---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/23)_

**Comment by zetok** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/23)_

**Pull request merged**
