### PR TITLE
Use specified length

### PR DESCRIPTION
**Pull request by Diadlo**
One the top of the spec variable length declared as `[0,]`

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/spec/60)

### CODE REVIEW

**Comment by robinlinden** [comment]
For Travis to pass you have to strip the superfluous whitespace in the tables.

**Comment by Diadlo** [comment]
@robinlinden Fixed

**Comment by iphydf** [comment]
Looks good, can you make this change on https://github.com/TokTok/hs-toxcore? We can then merge it back into the spec.

**Comment by Diadlo** [comment]
@iphydf Why spec moved under haskell implementation of toxcore?

**Comment by iphydf** [comment]
@Diadlo it has been there pretty much from the start. Why: because the implementation is next to the specification. We can look at the spec in latex and see the haskell model implementation right between the lines.

**Comment by Diadlo** [comment]
@iphydf Why not in c-toxcore? C model shouldn't be right between the lines?

**Comment by iphydf** [comment]
@Diadlo no, because C is not a model implementation. It's an efficient, verbose, and non-obvious implementation. The Haskell implementation is intended to be very clear, "obviously correct" (as opposed to "arguably correct", which is a property of the C implementation).

**Comment by iphydf** [comment]
Please enable the checkbox "Allow edits from maintainers." on the bottom right.

**Comment by Diadlo** [comment]
@iphydf Done

**Pull request closed without merging**
