### PR TITLE
Add basic integer type representations to the intro.

### PR DESCRIPTION
**Pull request by iphydf**
[Review on Reviewable](https://reviewable.io/reviews/toktok/tox-spec/27)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[spec.md, line 32 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/27#-KCHUfeyIFJ-oeD3x5O6:-KCHUfezyXgBNMe3BBes:91277321) ([raw file](https://github.com/toktok/tox-spec/blob/a69ab94df322e7fb2c976fa8173b8d749614ee4b/spec.md#L32)):_
Except that some parts of spec might say something different? E.g. in PR #26 encoding is LE.

"Unless stated otherwise" ?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/27)_

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[spec.md, line 32 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/27#-KCHUfeyIFJ-oeD3x5O6:-KCLhuHrbKB6ahx-IFif:-499146009) ([raw file](https://github.com/toktok/tox-spec/blob/a69ab94df322e7fb2c976fa8173b8d749614ee4b/spec.md#L32)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/27)_

**Comment by zetok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/27)_

**Comment by zetok** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/27)_

**Pull request merged**
