### PR TITLE
Rewrote part of the DHT sections on packet formats.

### PR DESCRIPTION
**Pull request by iphydf**
[Review on Reviewable](https://reviewable.io/reviews/toktok/tox-spec/21)

### CODE REVIEW

**Comment by zetok** [comment]
Generally, making packet structure less "redundant" in the spec appears to make it a lot harder to comprehend how each packet structure should look like.

---

Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions.

---

_[spec.md, line 23 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBnmEji0barVDjJBNy3:-KBnmEji0barVDjJBNy4:-676370370) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L23)):_
Is `[n, ]` really better than `[n, …]` ?

---

_[spec.md, line 339 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqVsxCRORAIIMjBcGt:-KBqVsxDICvx1LZ6VzRs:-1818131523) ([raw file](https://github.com/toktok/tox-spec/blob/5cbe98548f82acfa10f51646bdc3fea656af1c30/spec.md#L339)):_
Without this, it's harder to visualise how packet structure is supposed to look like.

---

_[spec.md, line 352 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqW6ctXdYg0ydeb15r:-KBqW6ctXdYg0ydeb15s:1064459590) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L352)):_
"inside" is kinda confusing, due to it sounding as if there was some sort of wrapper around data.

"Protocol Packets that are used in DHT consist of Packet Kind followed by DHT Packet data" ?

---

_[spec.md, line 358 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqXKpBnPbn5xW0TIO3:-KBqXKpCSQDrGf2-HKfr:-502315302) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L358)):_
Due to padding, size of the encrypted part is always at minimum `+ MACBYTES` (16 bytes) when encrypted. Minimal plain size seems to be 9 (Ping).

---

_[spec.md, line 360 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqaUkbx6UmVsywlfSe:-KBqaUkcElq1DuJasH6O:2109353702) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L360)):_
Given that "RPC Services" is part of the DHT Packet, shouldn't it be located "under" it, as its subsection? 

---

_[spec.md, line 363 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqd0RjtHOC-XGTyIKK:-KBqd0RjtHOC-XGTyIKL:-560135341) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L363)):_
Is "Ping ID" the best name? I.e. it seems to have a bit of capacity to be misleading - wouldn't it be better to call it differently, e.g. "Request ID" ?

On the other hand, "Request ID" can also be misleading :/

---

_[spec.md, line 372 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqe5ujz5J6rfdWA9Jc:-KBqe5ujz5J6rfdWA9Jd:-909322894) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L372)):_
Minimal length of payload in DHT Packet is 1 – smallest payload in DHT Packet is with Ping Req/Resp, which has 9 bytes.

---

_[spec.md, line 380 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqnHB6n634Nvqe6S30:-KBqnHB6n634Nvqe6S31:347695936) ([raw file](https://github.com/toktok/tox-spec/blob/5cbe98548f82acfa10f51646bdc3fea656af1c30/spec.md#L380)):_
I think that it would be nice to keep that info somewhere, even if spec isn't quite the right place for it.

---

_[spec.md, line 392 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqimRxZXQEugHidew5:-KBqimRxZXQEugHidew6:2106080796) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L392)):_
Err. This is really misleading, as opposed to the original text, since it sounds as if the encrypted text was the same, and not the plaintext.

Also, it's invalid, if 

> A Ping Packet contains just its Packet Kind.

is to be upheld - i.e. Ping packet consists _only_ of one byte.

---

_[spec.md, line 438 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqc7zvCvTguCWmXmAm:-KBqc7zvCvTguCWmXmAn:-2047173176) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L438)):_
Info regarding Packed Node is located under `## Node Info (packed node format)`.

Line can be removed, since it seems redundant, and this subsection needs some other name.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/21#-:-KBqmRafBvl6-VVJ7ypR:391096700)_

**Comment by iphydf** [comment]
That's true, but ideally an implementor wouldn't really care what the final packets look like. Each abstraction and each sub-packet should be understandable. There are two main concerns with the redundancy:
1. If the final packet structure becomes too complex, it becomes harder to comprehend as well.
2. If the packets all look very similar, finding the difference is a challenge.

---

Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions.

---

_[spec.md, line 23 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBnmEji0barVDjJBNy3:-KBqsKTzh9grUmoDQUy4:-1969891028) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L23)):_
It seems not better or worse. `[n,∞]` would be ideal, but both ∞ and … are unicode symbols. I'm not sure how they behave when e.g. [converted to PDF](https://gist.github.com/benmarwick/4fb6f222443493e3c864).

Which exact notation is chosen isn't that important, as long as it's consistent and specified.

---

_[spec.md, line 339 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqVsxCRORAIIMjBcGt:-KBr1uR0OYCB6epW1zaB:-88809667) ([raw file](https://github.com/toktok/tox-spec/blob/5cbe98548f82acfa10f51646bdc3fea656af1c30/spec.md#L339)):_
With it, it becomes ambiguous, because then does the DHT Packet have the packet kind repeated or is this byte already part of the Protocol Packet? The sentence immediately preceding the table is intended to clarify that.

---

_[spec.md, line 352 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqW6ctXdYg0ydeb15r:-KBqyF1RYtI3v3t04Vpw:-2002719982) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L352)):_
It's intended to convey the "wrapper" idea. The way I intend for the spec to work is that it not just specifies packet layouts and behaviour, but also provides higher level abstractions that are useful for implementing and reasoning about it. The fact that DHT Packets are sent inside Protocol Packets is purely informative, not normative. It might as well be transported in some other way.

---

_[spec.md, line 358 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqXKpBnPbn5xW0TIO3:-KBqtsRXpEef_dDK5QWD:-499146009) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L358)):_
Done.

---

_[spec.md, line 360 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqaUkbx6UmVsywlfSe:-KBqtt8huHZ_MgnaC6Q7:-301342528) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L360)):_
No, just like the DHT Packet is part of a Protocol Packet, it is wrapped within, but not hierarchically below it. In particular, in an implementation you'll want to have an abstraction of RPC Services that give you the wrapped packet (in case of ping it's just a bool).

---

_[spec.md, line 363 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqd0RjtHOC-XGTyIKK:-KBqy5Yw2Ob2EjCz0OcS:-1508424841) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L363)):_
I like Request ID better.

---

_[spec.md, line 372 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqe5ujz5J6rfdWA9Jc:-KBquS8tJgCwrRrB35i9:1392578983) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L372)):_
The RPC packet doesn't care, but you're right that it would be bad if a packet format existed with no payload. Clarified that.

---

_[spec.md, line 380 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqnHB6n634Nvqe6S30:-KBr1dYOmTDyLveFCQ2a:385679069) ([raw file](https://github.com/toktok/tox-spec/blob/5cbe98548f82acfa10f51646bdc3fea656af1c30/spec.md#L380)):_
Which info went missing? The last sentence is now "helps identify the response for a given request" in the rpc packet section.

---

_[spec.md, line 392 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqimRxZXQEugHidew5:-KBqwdVI1BEFeKLkUTvq:-910331869) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L392)):_
Clarified.

Ping Packet does only consist of one byte. It is transported within an RPC Packet, which consists of payload + 8 bytes. In the end you'll have `ProtocolPacket(kind, DhtPacket(pubkey, nonce, encrypted(RpcPacket(PingPacket(True), requestId))))` for a ping response. The "ping packet" part is just one byte.

If I add a clarifying sentence to the Ping Packet section, it would need to be added to every packet section as it would otherwise imply that it's only true for ping packets. Suggestions for where (not how) I should clarify this structure?

---

_[spec.md, line 438 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqc7zvCvTguCWmXmAm:-KBqxwuTyoO4FmTYqD9X:-609814302) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L438)):_
I agree, but not in this PR. I haven't started rewriting this section, yet.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/21#-:-KBr-BcYWwAe1d8dO9GD:-1641406069)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[spec.md, line 339 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqVsxCRORAIIMjBcGt:-KBrZevG8vGBkSFKHYdQ:1067754198) ([raw file](https://github.com/toktok/tox-spec/blob/5cbe98548f82acfa10f51646bdc3fea656af1c30/spec.md#L339)):_
Right. "Clarification" though to me sounds a bit as if Packet Kind byte was located after the contents of DHT Packet. Perhaps that's just how I perceive it.

---

_[spec.md, line 392 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqimRxZXQEugHidew5:-KBrb22mFALdaHQ5mu7P:1861247804) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L392)):_
Since it holds true for all RPC Packets, shouldn't it be clarified there?

---

_[spec.md, line 409 [r3]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBrh7sXTcNTgaJCJFDI:-KBrh7sXTcNTgaJCJFDJ:868706570) ([raw file](https://github.com/toktok/tox-spec/blob/cf0727da129b1ccce331fed85631619e158761d7/spec.md#L409)):_
I think that False/True "alone" is not enough, or at least not when seemingly nothing really points to `0x00`/`0x01` being the values of the "bool".

Or, if "bool" value is going to be used also elsewhere, perhaps something could be added to Introduction about it?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/21)_

**Comment by zetok** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/21)_

**Comment by nicoonoclaste** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

_[spec.md, line 211 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBsa9yZ2_6XG4EswmlR:-KBsa9yZ2_6XG4EswmlS:1570763249) ([raw file](https://github.com/toktok/tox-spec/blob/5cbe98548f82acfa10f51646bdc3fea656af1c30/spec.md#L211)):_
Specify the length unit (bytes)

---

_[spec.md, line 216 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBsaj9XuXZwy_WvRrHd:-KBsaj9Yd1H4sVAncxUK:-1529348815) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L216)):_
Should this be the place to specify a common endianess for all payloads?

---

_[spec.md, line 270 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBsawUW98uRvGkNGARI:-KBsawUW98uRvGkNGARJ:526678684) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L270)):_
Since you are uniformising on “node”, shouldn't you start with “all nodes in the Tox network [...] also called “Tox node” or “peer”” ?

---

_[spec.md, line 276 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBsbGcw3AkIbvTqm8Py:-KBsbGcw3AkIbvTqm8Pz:-165358038) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L276)):_
“ephemeral” rather than “temporary”, I would say.
(It makes it clearer that the key is a throw-away that is changed from time to time)

---

_[spec.md, line 283 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBseCPWTSDQYxvLU5mj:-KBseCPWTSDQYxvLU5mk:-394748233) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L283)):_
Is the algebraic background helpful?

---

_[spec.md, line 286 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBse3GnamT3pb8CGhyD:-KBse3GoVt2AE-jM0AjZ:-870347448) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L286)):_
“Distance is an [ordered monoid](https://en.wikipedia.org/wiki/Ordered_semigroup)”, otherwise none of that section makes sense.

---

_[spec.md, line 288 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBscKz7NyJUqEqG8z4x:-KBscKz8Gz40NnDeSoMd:2060073469) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L288)):_
“their Distance [to the node under consideration]”

---

_[spec.md, line 292 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBsccItC3x6XIW3LWWW:-KBsccItC3x6XIW3LWWX:608975444) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L292)):_
“co-domain”, not “result”

---

_[spec.md, line 309 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBscr4Rp8kKPQLZCdgZ:-KBscr4Rp8kKPQLZCdg_:-1131771359) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L309)):_
This should be “`d(x, y) == 0` iff `x == y`: two integers have a null XOR iff they are equal”.\
Otherwise, the constant function 0 would be a metric.

---

_[spec.md, line 327 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBseL5xmUBTOMYhE87B:-KBseL5xmUBTOMYhE87C:892104324) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L327)):_
Is that relevant ?

---

_[spec.md, line 361 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBsiEE6kH5UqjIUSKny:-KBsiEE7h4T8jagmRl7x:-1280666773) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L361)):_
It would be better, I think, to say “an authentication tag”, because Poly1305 by itself is “only” a one-time authenticator, and it is used here in an authenticated encryption construction.

---

_[spec.md, line 382 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBskgQ3UhdGtdikb5Ns:-KBskgQ4gz2RAINc0kUh:1576787459) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L382)):_
The “due to symmetric encryption” part is hard to understand.  Here is a stab at improving it:

> Due to the use of the same symmetric key in both communication directions, an encrypted
> Request is a valid encrypted Response, containing the same plaintext.  
> Parts of the protocol using RPC packets must take care to make Request payloads not be
> valid Response payloads; for instance, [Ping Packets](#ping-service) carry a boolean flag
> that indicate whether the payload corresponds to a Request or an Answer.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/21)_

**Comment by GrayHatter** [comment]
It also makes it easier to maintain, and keep everything up to date if we don't have to edit multiple places.

---

Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

_[spec.md, line 211 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBsa9yZ2_6XG4EswmlR:-KBsthoCEImDtrxI0yxY:474825619) ([raw file](https://github.com/toktok/tox-spec/blob/5cbe98548f82acfa10f51646bdc3fea656af1c30/spec.md#L211)):_
I suggest not. Everything in the spec should be in bytes.

---

_[spec.md, line 276 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBsbGcw3AkIbvTqm8Py:-KBsuGSp6pJEbIlE1aw8:1209524206) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L276)):_
Temporary is probably better in this case. It could last weeks-months if the tox instance never gets restarted.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/21#-:-KBsukwl2zxWUkMuJGi0:1380902841)_

**Comment by nicoonoclaste** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

_[spec.md, line 211 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBsa9yZ2_6XG4EswmlR:-KBwTnBYGHW9PhcpQOxS:1581067197) ([raw file](https://github.com/toktok/tox-spec/blob/5cbe98548f82acfa10f51646bdc3fea656af1c30/spec.md#L211)):_
There are a places in the spec where the unit is specified (and sometimes the value in bits is added).
If everything should be (unless specified) bytes, it should also be stated at the beginning (I might have missed it, but I didn't find such a definition).

---

_[spec.md, line 276 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBsbGcw3AkIbvTqm8Py:-KBwUJJ2MXnTljd2_vaA:1959896254) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L276)):_
My issue with temporary is that it makes it sound that it is used only until something else happens (and we switch to another key).
Should that be “session key” instead?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/21)_

**Comment by iphydf** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

_[spec.md, line 339 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqVsxCRORAIIMjBcGt:-KBwgXWdCq-gi2nzoeNS:1222793305) ([raw file](https://github.com/toktok/tox-spec/blob/5cbe98548f82acfa10f51646bdc3fea656af1c30/spec.md#L339)):_
With the packet structure tables merged, this is now clear.

---

_[spec.md, line 392 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBqimRxZXQEugHidew5:-KBwgGq2a-uwlTErHmSc:-1435956346) ([raw file](https://github.com/toktok/tox-spec/blob/83fab7c37d46ea30d5e7413ed26b4dd1adbcc8d6/spec.md#L392)):_
I've resolved to using XSLT to expand packet types in the output HTML.

---

_[spec.md, line 211 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBsa9yZ2_6XG4EswmlR:-KBwDwYbXi_7eUQz4THi:1383233942) ([raw file](https://github.com/toktok/tox-spec/blob/5cbe98548f82acfa10f51646bdc3fea656af1c30/spec.md#L211)):_
The default length unit is bytes, as specified in paragraph 3 of the introduction.

---

_[spec.md, line 216 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBsaj9XuXZwy_WvRrHd:-KBwETRG7GcBfyVPYZRa:618851790) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L216)):_
Added a sentence about integer encoding to Introduction paragraph 2.

---

_[spec.md, line 270 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBsawUW98uRvGkNGARI:-KBwFDLxNmRFL5xYapSC:-1530771663) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L270)):_
Agreed.

---

_[spec.md, line 276 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBsbGcw3AkIbvTqm8Py:-KBwcYWxjiTdZhvD2V1B:-1690949966) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L276)):_
Updated description and split into two paragraphs.

---

_[spec.md, line 283 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBseCPWTSDQYxvLU5mj:-KBwd060yiA8RPNTsMrm:146949350) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L283)):_
I think where possible, we should include the algebraic background of data types. This guides an implementation, because for example in C++ one could create a class representing a distance, and "ordered monoid" like you said is a simple way of saying "it has an operator <=, an operator+, and a zero".

Later on in the document we'll be talking about node sets and define operations on them. There, this terminology will be useful as well.

---

_[spec.md, line 286 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBse3GnamT3pb8CGhyD:-KBwcyYVUjpZd-PL7ilg:-499146009) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L286)):_
Done.

---

_[spec.md, line 288 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBscKz7NyJUqEqG8z4x:-KBwcmNgYwv_DFVQwKW_:-499146009) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L288)):_
Done.

---

_[spec.md, line 292 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBsccItC3x6XIW3LWWW:-KBwdlFnAMpgs3rQL7D6:-499146009) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L292)):_
Done.

---

_[spec.md, line 309 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBscr4Rp8kKPQLZCdgZ:-KBwe8kZhqk1JZOKSmBW:2080954295) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L309)):_
I had considered this, but decided to simplify. I've reverted that decision.

---

_[spec.md, line 327 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBseL5xmUBTOMYhE87B:-KBweQM5-k94kU6GJ7gf:-1081084963) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L327)):_
Not really. Removed.

---

_[spec.md, line 361 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBsiEE6kH5UqjIUSKny:-KBweZMiIpmgPv5bQ_ua:-392917790) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L361)):_
The reason for saying MAC is that [NaCl calls it that](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/include/sodium/crypto_box_curve25519xsalsa20poly1305.h#L34). Why is MAC a bad name for it?

---

_[spec.md, line 382 [r4]](https://reviewable.io:443/reviews/toktok/tox-spec/21#-KBskgQ3UhdGtdikb5Ns:-KBwfxMH8rOMMUKCbIj4:818816578) ([raw file](https://github.com/toktok/tox-spec/blob/3c15159b10c0a04212678e39243bda2cf4eab8d5/spec.md#L382)):_
Accepted this, rewrote it slightly. PTAL to see if it still means what you wanted it to express.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/21)_

**Pull request merged**
