### PR TITLE
Add missing packet kind.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/spec/41)

### CODE REVIEW

**Comment by Diadlo** [comment]
What about add details description. What is`Bootstrap Info`?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/spec/41#-:-KQ_UB2-DkbrnM6WbO1N:bdpzk00)_

**Comment by GrayHatter** [comment]
:lgtm: 

@diadlo set packet -> get info

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/spec/41#-:-KQi_TiM3Z4VlKGRnU4b:b-vjrxfz)_

**Comment by Diadlo** [comment]
@GrayHatter Thanks, but what info?)

**Comment by nicoonoclaste** [comment]
Agreed with @dialdo, we need a description of the bootstrap mechanism.
However, I would argue this is out of scope for this PR/patch.

:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/spec/41#-:-KRustnawWzxRetN0yao:bidx5st)_

**Pull request closed without merging**
