### PR TITLE
Added test protocol specification.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/tox-spec/32)

### CODE REVIEW

**Comment by zetok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/tox-spec/32)_

**Comment by iphydf** [comment]
Added the Nonce Increment test.

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[spec.md, line 4081 [r3]](https://reviewable.io:443/reviews/toktok/tox-spec/32#-KFAxE4JsW0XC3urNdAr:-KFAxE4JsW0XC3urNdAs:-929124074) ([raw file](https://github.com/toktok/tox-spec/blob/6bff4c0edb023cc60d531de30765768517814a62/spec.md#L4081)):_
`#basic-data-encoding` doesn't specify what actual tests (if there are any) are supposed to be.

---

_[spec.md, line 4083 [r3]](https://reviewable.io:443/reviews/toktok/tox-spec/32#-KFAwbewO1IRnz5kPDHf:-KFAwbewO1IRnz5kPDHg:1827526909) ([raw file](https://github.com/toktok/tox-spec/blob/6bff4c0edb023cc60d531de30765768517814a62/spec.md#L4083)):_
is test `BinaryDecode NodeInfo` still available?

And is there a list of tests that are actually implemented? I mean, it implies that tests are limited by the existence of deconstructed values of data structures, but..

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/tox-spec/32)_

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[spec.md, line 4081 [r3]](https://reviewable.io:443/reviews/toktok/tox-spec/32#-KFAxE4JsW0XC3urNdAr:-KFB6UTsijXubL3Me1V1:941096265) ([raw file](https://github.com/toktok/tox-spec/blob/6bff4c0edb023cc60d531de30765768517814a62/spec.md#L4081)):_
Clarified this section a bit.

---

_[spec.md, line 4083 [r3]](https://reviewable.io:443/reviews/toktok/tox-spec/32#-KFAwbewO1IRnz5kPDHf:-KFB6bh_DtJEYGVmTnIM:1133738816) ([raw file](https://github.com/toktok/tox-spec/blob/6bff4c0edb023cc60d531de30765768517814a62/spec.md#L4083)):_
Is this now clearer?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/tox-spec/32)_

**Comment by zetok** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/tox-spec/32)_

**Pull request merged**
