### PR TITLE
Fix Travis CI badge.

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/toktok/spec/53)

### CODE REVIEW

**Review by gjedeer — APPROVED** [review]
LGTM

**Comment by robinlinden** [comment]
@gjedeer Can you do a review using Reviewable? I'm unable to merge anything not :lgtm:'d on there.

**Comment by gjedeer** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/spec/53#-:-KybJvHGO__JlUzIJrgA:b-jbsf8z)*

**Comment by gjedeer** [comment]
Is that enough? Reviewable interface is so odd.

**Comment by robinlinden** [comment]
@gjedeer That's perfect, thank you. :>

**Comment by iphydf** [comment]
@robinlinden this needs rebase then merge.

**Comment by iphydf** [comment]
Can you also add something like this to the readme:

```markdown
**The source of truth for the documentation here is in the
[hs-toxcore](https://github.com/TokTok/hs-toxcore) repository. Don't make changes directly here,
as they will be overwritten.**
```

**Comment by iphydf** [comment]
Please enable the checkbox "Allow edits from maintainers." on the bottom right.

**Review by iphydf — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/toktok/spec/53#-:-LJkJ3UL4ogucuP7IHvE:b-jbsf8z)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
