### PR TITLE
Formatting

### PR DESCRIPTION
**Pull request by iphydf**
[Review on Reviewable](https://reviewable.io/reviews/toktok/tox-spec/13)

### CODE REVIEW

**Comment by iphydf** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[spec.md, line 2692 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/13#-KBIb5x1VOHtH3C7fSOJ:-KBIb5x2tepphcZX2pIb:-2066091974) ([raw file](https://github.com/toktok/tox-spec/blob/402c73b0e2b4f13d8b4760cff8f9034a55bd0667/spec.md#L2692)):_
@irungentoo: Which nonce?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/13)_

**Comment by zetok** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[spec.md, line 2733 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/13#-KBKguqehSASZOPmn0Ji:-KBKguqehSASZOPmn0Jj:1407898408) ([raw file](https://github.com/toktok/tox-spec/blob/402c73b0e2b4f13d8b4760cff8f9034a55bd0667/spec.md#L2733)):_
`uint8_t`

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/13)_

**Comment by iphydf** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[spec.md, line 2733 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/13#-KBKguqehSASZOPmn0Ji:-KBNbcjAZNJraB_tBYFj:-499146009) ([raw file](https://github.com/toktok/tox-spec/blob/402c73b0e2b4f13d8b4760cff8f9034a55bd0667/spec.md#L2733)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/13)_

**Comment by iphydf** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[spec.md, line 2692 [r1]](https://reviewable.io:443/reviews/toktok/tox-spec/13#-KBIb5x1VOHtH3C7fSOJ:-KBNczFhOplWgLQ8DnB_:-778254750) ([raw file](https://github.com/toktok/tox-spec/blob/402c73b0e2b4f13d8b4760cff8f9034a55bd0667/spec.md#L2692)):_
Moved the question to the Tox-Docs repo.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/13)_

**Comment by zetok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/toktok/tox-spec/13)_

**Pull request merged**
